name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code into the Go module directory"
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.46.2

      - name: Lint
        run: golangci-lint run -v -c .golangci.yml

      - name: Test
        run: make test coverage
